INSERT INTO types_ressources(nom_ressource) VALUES ("Galet");
INSERT INTO types_ressources(nom_ressource) VALUES ("Erable Rouge");
INSERT INTO types_ressources(nom_ressource) VALUES ("Granite");
INSERT INTO types_ressources(nom_ressource) VALUES ("Bouleau");
INSERT INTO types_ressources(nom_ressource) VALUES ("Mahogany");
INSERT INTO types_ressources(nom_ressource) VALUES ("Acajou");
INSERT INTO types_ressources(nom_ressource) VALUES ("Amethyste");
INSERT INTO types_ressources(nom_ressource) VALUES ("Cactus");
INSERT INTO types_ressources(nom_ressource) VALUES ("Agate du desert");
INSERT INTO types_ressources(nom_ressource) VALUES ("Agate de feu");
INSERT INTO types_ressources(nom_ressource) VALUES ("Palmier");
INSERT INTO types_ressources(nom_ressource) VALUES ("Acacia");
INSERT INTO types_ressources(nom_ressource) VALUES ("Celestine");
INSERT INTO types_ressources(nom_ressource) VALUES ("Calcite");
INSERT INTO types_ressources(nom_ressource) VALUES ("Arbre mort");
INSERT INTO types_ressources(nom_ressource) VALUES ("Sapin");
INSERT INTO types_ressources(nom_ressource) VALUES ("Magnesite");